### ISSUE TITLE
Using dynamic_columns & column alias

### ISSUE THREAD

**Issue by undernorthernsky** [rbock/sqlpp11#191]
Not sure if this is a bug; I am trying something like this:

```
const auto processes = processes_sql::Processes{};
const auto workflows = processes_sql::Workflows{};

SQLPP_ALIAS_PROVIDER(A);
SQLPP_ALIAS_PROVIDER(B);

auto find_query = sqlpp::dynamic_select(db).dynamic_columns(processes.id.as(A))
    .dynamic_from(processes).unconditionally();
find_query.from.add(sqlpp::dynamic_join(workflows).on(processes.workflowId == workflows.id));
find_query.selected_columns.add(sqlpp::without_table_check(workflows.txt.as(B)));
```

This causes a static assert failure within `without_table_check`; when commenting the static assert the code compiles and works as expected.
I've tried a number of variations but can't get it to work - any hints?
Note: only tested with 0.45 so far, will try a more recent version.

**Comment by rbock** [comment]
That definitely is a bug. Thanks for the report!

Will fix asap.

**Comment by rbock** [comment]
For the moment, it will work if you omit the `.as(B)`.

**Comment by rbock** [comment]
I pushed a fix to develop. Please check.

Best,

Roland

**Comment by undernorthernsky** [comment]
Thanks, that does fix the error.

I also have a small variation of the same(?) problem that still fails; is there a better way to conditionally add a multi-table join?
```
auto find_query = sqlpp::dynamic_select(db).dynamic_columns(…).from(processes)…;
…
if (foo) {
    find_query.from.add(sqlpp::dynamic_join(processTrees).on(processes.id == processTrees.pId));
    find_query.from.add(sqlpp::without_table_check(sqlpp::dynamic_join(treeVals)
      .on(processTrees.vId == treeVals.id)));
}

// sql fragment
SELECT … FROM processes … INNER JOIN process_trees ON (processes.id=process_trees.p_id)
  INNER JOIN tree_values ON (process_trees.v_id=tree_values.id) …
```

**Comment by rbock** [comment]
Haven't tried yet, but I guess you should be fine by just wrapping `processTrees.vId == treeVals.id` in `sqlpp::without_table_check` instead of the whole `dynamic_join`.

**Comment by undernorthernsky** [comment]
Yep, works; and looks clearer anyway.

Thanks for your help.

By the way: impressive piece of work!
